# Generated by Django 4.1 on 2022-09-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_register_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('team_name', models.CharField(max_length=100)),
                ('statement', models.CharField(max_length=100)),
            ],
        ),
    ]
