# Generated by Django 4.1 on 2022-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='organization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
